pipeline {
    agent any

    stages {
        stage('Checkout GIT') {
            steps {
                echo 'Pulling from Git...'
                git branch: 'master',
                    url: 'https://github.com/mohamedachrefsamaali/ProjetDevOps.git'
            }
        }

        stage('Compile') {
            steps {
                script {
                dir('timesheet-devops'){
                    sh 'mvn clean compile'
                    }
                }
            }
        }
    }
}
